name: build

concurrency: 
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

env:
  PACKAGE_DIRECTORY: game_overlay
  PACKAGE_NAME: game-overlay
  BUILD_CONFIGURATION: RelWithDebInfo
  BUILD_DIRECTORY: "build"
  DISTRIBUTE_DIRECTORY: "distribute"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Check for cached build
        id: cache-check
        uses: actions/cache@v2
        with:
          path: ${{env.BUILD_DIRECTORY}}
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Install dependencies
        if: steps.cache-check.outputs.cache-hit != 'true'
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Add MSBuild to PATH
        if: steps.cache-check.outputs.cache-hit != 'true'
        uses: microsoft/setup-msbuild@v1
      - name: Configure
        if: steps.cache-check.outputs.cache-hit != 'true'
        run: cmake -H"${{ github.workspace }}" -B"${{env.BUILD_DIRECTORY}}" -G"Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX="${{env.INSTALL_PACKAGE_PATH}}"
        env:
          INSTALL_PACKAGE_PATH: "${{env.BUILD_DIRECTORY}}/${{env.DISTRIBUTE_DIRECTORY}}/${{env.PACKAGE_DIRECTORY}}"
      - name: Build
        if: steps.cache-check.outputs.cache-hit != 'true'
        run: cmake --build "${{env.BUILD_DIRECTORY}}" --target install --config ${{env.BUILD_CONFIGURATION}}
      - name: Cache build
        if: steps.cache-check.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: ${{env.BUILD_DIRECTORY}}
          key: ${{ runner.os }}-build-${{ github.sha }}

  upload_debug:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Get build from cache
        uses: actions/cache@v2
        with:
          path: ${{env.BUILD_DIRECTORY}}
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Fetch symsrv-scripts
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          repository: stream-labs/symsrv-scripts
          path: symsrv-scripts
      - name: Run symbol server scripts
        run: ./symsrv-scripts/main.bat "${{ github.workspace }}/symsrv-scripts" ".\main.ps1 -localSourceDir '${{ github.workspace }}' -repo_userId 'stream-labs' -repo_name 'streamlabs-overlay' -repo_branch '${{ github.sha }}'"
        env:
          AWS_SYMB_ACCESS_KEY_ID: ${{secrets.AWS_SYMB_ACCESS_KEY_ID}}
          AWS_SYMB_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        shell: powershell

  upload_release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Get build from cache
        uses: actions/cache@v2
        with:
          path: ${{env.BUILD_DIRECTORY}}
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Put version into package.json
        run: node scripts/bump-version.js ${{ steps.get_version.outputs.VERSION }} ${{env.PACKAGE_PATH}}
        env:
          PACKAGE_PATH: "${{env.BUILD_DIRECTORY}}/${{env.DISTRIBUTE_DIRECTORY}}/${{env.PACKAGE_DIRECTORY}}"
      - name: Tar artifact for deployment
        run: tar -cvzf ${{env.TARGET_ARTIFACT}}.tar.gz -C ${{env.INSTALL_DISTRIBUTE_PATH}} ${{env.PACKAGE_DIRECTORY}}
        env:
          TARGET_ARTIFACT: ${{env.PACKAGE_NAME}}-${{ steps.get_version.outputs.VERSION }}-win64
          INSTALL_DISTRIBUTE_PATH: "${{env.BUILD_DIRECTORY}}/${{env.DISTRIBUTE_DIRECTORY}}"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_SYMB_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-west-2
      - name: Deploy
        run: aws s3 cp ${{env.TARGET_ARTIFACT}}-win64.tar.gz s3://obs-studio-deployment --acl public-read
        env:
          TARGET_ARTIFACT: ${{env.PACKAGE_NAME}}-${{ steps.get_version.outputs.VERSION }}-win64