name: build

concurrency: 
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_CONFIGURATION: RelWithDebInfo
  BUILD_DIRECTORY: "build"
  DISTRIBUTE_DIRECTORY: "distribute"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Configure
        run: cmake -H"${{ github.workspace }}" -B"${{env.BUILD_DIRECTORY}}" -G"Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX="${{env.INSTALL_DISTRIBUTE_PATH}}"
        env:
          INSTALL_DISTRIBUTE_PATH: "${{env.BUILD_DIRECTORY}}/${{env.DISTRIBUTE_DIRECTORY}}/game_overlay"

      - name: Build
        run: cmake --build "${{env.BUILD_DIRECTORY}}" --target install --config ${{env.BUILD_CONFIGURATION}}
  publish:
    needs: build
    if: startsWith(github.ref_type, 'tags')
    steps:
      - name: Fetch symsrv-scripts
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          repository: stream-labs/symsrv-scripts
          path: symsrv-scripts

      - name: Run symbol server scripts
        run: ./symsrv-scripts/main.bat "${{ github.workspace }}/symsrv-scripts" ".\main.ps1 -localSourceDir '${{ github.workspace }}' -repo_userId 'stream-labs' -repo_name 'streamlabs-overlay' -repo_branch '${{env.GITHUB_SHA}}'"
        env:
          AWS_SYMB_ACCESS_KEY_ID: ${{secrets.AWS_SYMB_ACCESS_KEY_ID}}
          AWS_SYMB_SECRET_ACCESS_KEY: ${{secrets.AWS_SYMB_SECRET_ACCESS_KEY}}

      - name: Tar artifact for deployment
        run: tar -zcf release-win64.tar.gz ./build/* -r
  publish_non_tag:
    needs: build
    steps:
      - name: Fetch symsrv-scripts
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          repository: stream-labs/symsrv-scripts
          path: symsrv-scripts

      - name: Run symbol server scripts
        run: ./symsrv-scripts/main.bat "${{ github.workspace }}/symsrv-scripts" ".\main.ps1 -localSourceDir '${{ github.workspace }}' -repo_userId 'stream-labs' -repo_name 'streamlabs-overlay' -repo_branch '${{env.GITHUB_SHA}}'"
        env:
          AWS_SYMB_ACCESS_KEY_ID: ${{secrets.AWS_SYMB_ACCESS_KEY_ID}}
          AWS_SYMB_SECRET_ACCESS_KEY: ${{secrets.AWS_SYMB_SECRET_ACCESS_KEY}}

      - name: Tar artifact for deployment
        run: tar -zcf release-win64.tar.gz ./build/* -r